version: "2"

run:
  timeout: 5m
  tests: true

linters:
  enable:
    - errcheck
    - govet
    - staticcheck
    - unused

  settings:
    errcheck:
      exclude-functions:
        - (*os.File).Close
        - (*net/http.Response).Body.Close
        - os.RemoveAll
        - os.Remove

issues:
  max-per-linter: 0
  max-same-issues: 0
  
  exclude:
    - "Error return value of `os.RemoveAll` is not checked"
    - "Error return value of.*Close.*is not checked"
    - "Error return value of `os.MkdirAll` is not checked"
    - "benchmark_test.go:.*Error return value"
  
  exclude-files:
    - "benchmark_test.go"