version: "2"

run:
  timeout: 5m
  tests: true

linters:
  enable:
    - errcheck
    - govet
    - staticcheck
    - unused

  settings:
    errcheck:
      exclude-functions:
        - (*os.File).Close
        - (*net/http.Response).Body.Close
        - os.RemoveAll
        - os.Remove

issues:
  exclude-rules:
    - path: _test\.go
      text: "Error return value of `os.RemoveAll` is not checked"
      linters:
        - errcheck
    - path: benchmark_test\.go
      linters:
        - errcheck