version: "2"

run:
  timeout: 5m
  tests: true

linters:
  default: none
  enable:
    - errcheck
    - govet
    - staticcheck
    - unused
  
  settings:
    errcheck:
      exclude-functions:
        - (*os.File).Close
        - (*net/http.Response).Body.Close
        - os.RemoveAll
        - os.Remove
        - os.MkdirAll
        - os.Rename
        - (*os/exec.Cmd).Run
        - (*os.File).Sync
        - fmt.Printf
        - fmt.Print
        - fmt.Println

  exclusions:
    # Enable standard exclusion presets
    presets:
      - std-error-handling
      - common-false-positives
    
    # Warn about unused exclusion rules
    warn-unused: true
    
    # Custom exclusion rules
    rules:
      - path: benchmark_test\.go
        linters:
          - errcheck
      - path: .*_test\.go
        text: "Error return value of `os.RemoveAll` is not checked"
        linters:
          - errcheck
      - text: "Error return value of.*StopService.*is not checked"
        linters:
          - errcheck
      - text: "Error return value of.*DisableService.*is not checked"
        linters:
          - errcheck
      - text: "Error return value of.*PrintSystemInfo.*is not checked"
        linters:
          - errcheck
      - text: "Error return value of.*DetectSystem.*is not checked"
        linters:
          - errcheck